# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Latest IJ

on:
  schedule:
  - cron: "0 0 * * *"

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'gradle'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build --continue -PideaVersion=LATEST-EAP-SNAPSHOT
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test-reports
          path: |
            build/test-results/**/*.xml
            build/jacoco/
