# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Latest IJ

on:
  schedule:
  - cron: "0 0 * * *"
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v5

      # Set up Java environment for the next steps
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      # Setup Gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5

      - name: Build with Gradle
        run: |
          LATEST_EAP_SNAPSHOT=$(./gradlew printProductsReleases | grep 'IC-' | head -n 1 | cut -d'-' -f2)
          echo "building using latest EAP version $LATEST_EAP_SNAPSHOT"
          ./gradlew check --continue -PplatformVersion=$LATEST_EAP_SNAPSHOT

      - name: Collect Tests Result
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-reports
          path: |
            path: ${{ github.workspace }}/build/reports/tests
            path: ${{ github.workspace }}/build/jacoco/