# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Integration tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
    - name: Run integration tests
      run: |
        sudo tcpdump -nn -i any -w sntp.cap &
        sleep 1
        chmod +x gradlew
        xvfb-run ./gradlew integrationTest --info
    - name: Upload capture
      if: always()
      run: |
        sleep 1
        sudo kill -2 $(pgrep tcpdump)
        sleep 1
    - uses: actions/upload-artifact@v4
      with:
        name: tcpdump
        path: sntp.cap
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ runner.os }}-integration-test-reports
        path: build/reports/tests/integrationTest
      if: always()
    - name: Archiving screenshots
      uses: actions/upload-artifact@v4
      with: 
        name: ${{ runner.os }}-screenshots
        path: |
          build/screenshots/
      if: always()
      
#  build-macos:
#    runs-on: macos-latest
#
#    steps:
#    - uses: actions/checkout@v4
#    - name: Set up JDK 17
#      uses: actions/setup-java@v4
#      with:
#        distribution: temurin
#        java-version: 17
#    - name: Run integration tests
#      run: |
#        ./gradlew integrationTest --info
#    - uses: actions/upload-artifact@v4
#      with:
#        name: ${{ runner.os }}-integration-test-reports
#        path: build/reports/tests/integrationTest
#      if: always()
#    - name: Archiving screenshots
#      uses: actions/upload-artifact@v4
#      with:
#        name: ${{ runner.os }}-screenshots
#        path: |
#          build/screenshots/
#      if: always()
      
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
    - name: Run integration tests
      run: |
        .\gradlew.bat integrationTest --info
      shell: powershell
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ runner.os }}-integration-test-reports
        path: build\reports\tests\integrationTest
      if: always()
    - name: Archiving screenshots
      uses: actions/upload-artifact@v4
      with: 
        name: ${{ runner.os }}-screenshots
        path: |
          build\screenshots\
      if: always()
